/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'author' : string,
  'summary' : string,
  'isFeatured' : boolean,
  'category' : string,
  'fileUrl' : string,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'githubUrl' : string,
  'demoUrl' : string,
  'category' : string,
  'techStack' : Array<string>,
}
export interface ResumeContent {
  'linkedin' : string,
  'about' : string,
  'tagline' : string,
  'name' : string,
  'email' : string,
  'careerObjective' : string,
  'github' : string,
  'resumeFileUrl' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, bigint, boolean, string],
    bigint
  >,
  'addProject' : ActorMethod<
    [string, Array<string>, string, string, string, string],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getFeaturedPost' : ActorMethod<[], [] | [BlogPost]>,
  'getPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getResumeContent' : ActorMethod<[], ResumeContent>,
  'initializeBlogs' : ActorMethod<[], undefined>,
  'initializeData' : ActorMethod<[], undefined>,
  'initializeProjects' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, bigint], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, bigint, boolean, string],
    boolean
  >,
  'updateProject' : ActorMethod<
    [bigint, string, Array<string>, string, string, string, string],
    boolean
  >,
  'updateResumeContent' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];