/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'githubUrl' : IDL.Text,
  'demoUrl' : IDL.Text,
  'category' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const ResumeContent = IDL.Record({
  'linkedin' : IDL.Text,
  'about' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'careerObjective' : IDL.Text,
  'github' : IDL.Text,
  'resumeFileUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getFeaturedPost' : IDL.Func([], [IDL.Opt(BlogPost)], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getResumeContent' : IDL.Func([], [ResumeContent], ['query']),
  'initializeBlogs' : IDL.Func([], [], []),
  'initializeData' : IDL.Func([], [], []),
  'initializeProjects' : IDL.Func([], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateResumeContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'githubUrl' : IDL.Text,
    'demoUrl' : IDL.Text,
    'category' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const ResumeContent = IDL.Record({
    'linkedin' : IDL.Text,
    'about' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'careerObjective' : IDL.Text,
    'github' : IDL.Text,
    'resumeFileUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getFeaturedPost' : IDL.Func([], [IDL.Opt(BlogPost)], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'getResumeContent' : IDL.Func([], [ResumeContent], ['query']),
    'initializeBlogs' : IDL.Func([], [], []),
    'initializeData' : IDL.Func([], [], []),
    'initializeProjects' : IDL.Func([], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateResumeContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };