/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const Experience = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'accentColor' : IDL.Text,
  'company' : IDL.Text,
  'badge' : IDL.Text,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'itemOrder' : IDL.Nat,
  'mediaUrl' : IDL.Text,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
  'category' : IDL.Text,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishedAt' : IDL.Int,
  'author' : IDL.Text,
  'summary' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : IDL.Text,
  'fileUrl' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'githubUrl' : IDL.Text,
  'demoUrl' : IDL.Text,
  'category' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const BlogViewStat = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'viewCount' : IDL.Nat,
});
export const ProjectViewStat = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'viewCount' : IDL.Nat,
});
export const AnalyticsData = IDL.Record({
  'topBlogs' : IDL.Vec(BlogViewStat),
  'topProjects' : IDL.Vec(ProjectViewStat),
  'visitorCount' : IDL.Nat,
  'resumeDownloadCount' : IDL.Nat,
});
export const ProfileMeta = IDL.Record({
  'instagram' : IDL.Text,
  'currentlyBuilding' : IDL.Text,
  'profileImageUrl' : IDL.Text,
});
export const ResumeContent = IDL.Record({
  'linkedin' : IDL.Text,
  'about' : IDL.Text,
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'careerObjective' : IDL.Text,
  'github' : IDL.Text,
  'resumeFileUrl' : IDL.Text,
});
export const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Nat });
export const SkillCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'accentColor' : IDL.Text,
  'skills' : IDL.Vec(Skill),
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addExperience' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addMediaItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addProject' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteExperience' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteMediaItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
  'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
  'getAllMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
  'getFeaturedPost' : IDL.Func([], [IDL.Opt(BlogPost)], ['query']),
  'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getProfileMeta' : IDL.Func([], [ProfileMeta], ['query']),
  'getResumeContent' : IDL.Func([], [ResumeContent], ['query']),
  'getSkillCategories' : IDL.Func([], [IDL.Vec(SkillCategory)], ['query']),
  'initializeBlogs' : IDL.Func([], [], []),
  'initializeData' : IDL.Func([], [], []),
  'initializeExperiences' : IDL.Func([], [], []),
  'initializeMediaItems' : IDL.Func([], [], []),
  'initializeProjects' : IDL.Func([], [], []),
  'initializeSkills' : IDL.Func([], [], []),
  'recordBlogView' : IDL.Func([IDL.Nat], [], []),
  'recordProjectView' : IDL.Func([IDL.Nat], [], []),
  'recordResumeDownload' : IDL.Func([], [], []),
  'recordVisit' : IDL.Func([], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateExperience' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateMediaItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Bool],
      [],
    ),
  'updateProfileMeta' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateProject' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateResumeContent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateSkillCategory' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(Skill)],
      [IDL.Bool],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const Experience = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'accentColor' : IDL.Text,
    'company' : IDL.Text,
    'badge' : IDL.Text,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'itemOrder' : IDL.Nat,
    'mediaUrl' : IDL.Text,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
    'category' : IDL.Text,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishedAt' : IDL.Int,
    'author' : IDL.Text,
    'summary' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : IDL.Text,
    'fileUrl' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'githubUrl' : IDL.Text,
    'demoUrl' : IDL.Text,
    'category' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const BlogViewStat = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'viewCount' : IDL.Nat,
  });
  const ProjectViewStat = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'viewCount' : IDL.Nat,
  });
  const AnalyticsData = IDL.Record({
    'topBlogs' : IDL.Vec(BlogViewStat),
    'topProjects' : IDL.Vec(ProjectViewStat),
    'visitorCount' : IDL.Nat,
    'resumeDownloadCount' : IDL.Nat,
  });
  const ProfileMeta = IDL.Record({
    'instagram' : IDL.Text,
    'currentlyBuilding' : IDL.Text,
    'profileImageUrl' : IDL.Text,
  });
  const ResumeContent = IDL.Record({
    'linkedin' : IDL.Text,
    'about' : IDL.Text,
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'careerObjective' : IDL.Text,
    'github' : IDL.Text,
    'resumeFileUrl' : IDL.Text,
  });
  const Skill = IDL.Record({ 'name' : IDL.Text, 'level' : IDL.Nat });
  const SkillCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'accentColor' : IDL.Text,
    'skills' : IDL.Vec(Skill),
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addExperience' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addMediaItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addProject' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text), IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteExperience' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteMediaItem' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteProject' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactSubmission)], ['query']),
    'getAllExperiences' : IDL.Func([], [IDL.Vec(Experience)], ['query']),
    'getAllMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsData], ['query']),
    'getFeaturedPost' : IDL.Func([], [IDL.Opt(BlogPost)], ['query']),
    'getPostsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'getProfileMeta' : IDL.Func([], [ProfileMeta], ['query']),
    'getResumeContent' : IDL.Func([], [ResumeContent], ['query']),
    'getSkillCategories' : IDL.Func([], [IDL.Vec(SkillCategory)], ['query']),
    'initializeBlogs' : IDL.Func([], [], []),
    'initializeData' : IDL.Func([], [], []),
    'initializeExperiences' : IDL.Func([], [], []),
    'initializeMediaItems' : IDL.Func([], [], []),
    'initializeProjects' : IDL.Func([], [], []),
    'initializeSkills' : IDL.Func([], [], []),
    'recordBlogView' : IDL.Func([IDL.Nat], [], []),
    'recordProjectView' : IDL.Func([IDL.Nat], [], []),
    'recordResumeDownload' : IDL.Func([], [], []),
    'recordVisit' : IDL.Func([], [], []),
    'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Int], [], []),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateExperience' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateMediaItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Bool],
        [],
      ),
    'updateProfileMeta' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateProject' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateResumeContent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateSkillCategory' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(Skill)],
        [IDL.Bool],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };