/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'topBlogs' : Array<BlogViewStat>,
  'topProjects' : Array<ProjectViewStat>,
  'visitorCount' : bigint,
  'resumeDownloadCount' : bigint,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'publishedAt' : bigint,
  'author' : string,
  'summary' : string,
  'isFeatured' : boolean,
  'category' : string,
  'fileUrl' : string,
}
export interface BlogViewStat {
  'id' : bigint,
  'title' : string,
  'viewCount' : bigint,
}
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Experience {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'tags' : Array<string>,
  'description' : string,
  'accentColor' : string,
  'company' : string,
  'badge' : string,
}
export interface MediaItem {
  'id' : bigint,
  'title' : string,
  'itemOrder' : bigint,
  'mediaUrl' : string,
  'caption' : string,
  'mediaType' : string,
  'category' : string,
}
export interface ProfileMeta {
  'instagram' : string,
  'currentlyBuilding' : string,
  'profileImageUrl' : string,
}
export interface Project {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'githubUrl' : string,
  'demoUrl' : string,
  'category' : string,
  'techStack' : Array<string>,
}
export interface ProjectViewStat {
  'id' : bigint,
  'title' : string,
  'viewCount' : bigint,
}
export interface ResumeContent {
  'linkedin' : string,
  'about' : string,
  'tagline' : string,
  'name' : string,
  'email' : string,
  'careerObjective' : string,
  'github' : string,
  'resumeFileUrl' : string,
}
export interface Skill { 'name' : string, 'level' : bigint }
export interface SkillCategory {
  'id' : bigint,
  'name' : string,
  'accentColor' : string,
  'skills' : Array<Skill>,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, bigint, boolean, string],
    bigint
  >,
  'addExperience' : ActorMethod<
    [string, string, string, string, string, Array<string>, string],
    bigint
  >,
  'addMediaItem' : ActorMethod<
    [string, string, string, string, string, bigint],
    bigint
  >,
  'addProject' : ActorMethod<
    [string, Array<string>, string, string, string, string],
    bigint
  >,
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteExperience' : ActorMethod<[bigint], boolean>,
  'deleteMediaItem' : ActorMethod<[bigint], boolean>,
  'deleteProject' : ActorMethod<[bigint], boolean>,
  'getAllContacts' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllExperiences' : ActorMethod<[], Array<Experience>>,
  'getAllMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getAllPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllProjects' : ActorMethod<[], Array<Project>>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getFeaturedPost' : ActorMethod<[], [] | [BlogPost]>,
  'getPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getProfileMeta' : ActorMethod<[], ProfileMeta>,
  'getResumeContent' : ActorMethod<[], ResumeContent>,
  'getSkillCategories' : ActorMethod<[], Array<SkillCategory>>,
  'initializeBlogs' : ActorMethod<[], undefined>,
  'initializeData' : ActorMethod<[], undefined>,
  'initializeExperiences' : ActorMethod<[], undefined>,
  'initializeMediaItems' : ActorMethod<[], undefined>,
  'initializeProjects' : ActorMethod<[], undefined>,
  'initializeSkills' : ActorMethod<[], undefined>,
  'recordBlogView' : ActorMethod<[bigint], undefined>,
  'recordProjectView' : ActorMethod<[bigint], undefined>,
  'recordResumeDownload' : ActorMethod<[], undefined>,
  'recordVisit' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<[string, string, string, bigint], undefined>,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, bigint, boolean, string],
    boolean
  >,
  'updateExperience' : ActorMethod<
    [bigint, string, string, string, string, string, Array<string>, string],
    boolean
  >,
  'updateMediaItem' : ActorMethod<
    [bigint, string, string, string, string, string, bigint],
    boolean
  >,
  'updateProfileMeta' : ActorMethod<[string, string, string], undefined>,
  'updateProject' : ActorMethod<
    [bigint, string, Array<string>, string, string, string, string],
    boolean
  >,
  'updateResumeContent' : ActorMethod<
    [string, string, string, string, string, string, string, string],
    undefined
  >,
  'updateSkillCategory' : ActorMethod<
    [bigint, string, string, Array<Skill>],
    boolean
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];