/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    publishedAt: bigint;
    author: string;
    summary: string;
    isFeatured: boolean;
    category: string;
    fileUrl: string;
}
export interface BlogViewStat {
    id: bigint;
    title: string;
    viewCount: bigint;
}
export interface ProfileMeta {
    instagram: string;
    currentlyBuilding: string;
    profileImageUrl: string;
}
export interface Skill {
    name: string;
    level: bigint;
}
export interface Experience {
    id: bigint;
    title: string;
    date: string;
    tags: Array<string>;
    description: string;
    accentColor: string;
    company: string;
    badge: string;
}
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export interface ProjectViewStat {
    id: bigint;
    title: string;
    viewCount: bigint;
}
export interface MediaItem {
    id: bigint;
    title: string;
    itemOrder: bigint;
    mediaUrl: string;
    caption: string;
    mediaType: string;
    category: string;
}
export interface SkillCategory {
    id: bigint;
    name: string;
    accentColor: string;
    skills: Array<Skill>;
}
export interface ResumeContent {
    linkedin: string;
    about: string;
    tagline: string;
    name: string;
    email: string;
    careerObjective: string;
    github: string;
    resumeFileUrl: string;
}
export interface Project {
    id: bigint;
    title: string;
    description: string;
    githubUrl: string;
    demoUrl: string;
    category: string;
    techStack: Array<string>;
}
export interface AnalyticsData {
    topBlogs: Array<BlogViewStat>;
    topProjects: Array<ProjectViewStat>;
    visitorCount: bigint;
    resumeDownloadCount: bigint;
}
export interface backendInterface {
    addBlogPost(title: string, category: string, summary: string, content: string, author: string, publishedAt: bigint, isFeatured: boolean, fileUrl: string): Promise<bigint>;
    addExperience(title: string, company: string, badge: string, date: string, description: string, tags: Array<string>, accentColor: string): Promise<bigint>;
    addMediaItem(title: string, category: string, caption: string, mediaUrl: string, mediaType: string, itemOrder: bigint): Promise<bigint>;
    addProject(title: string, techStack: Array<string>, description: string, category: string, githubUrl: string, demoUrl: string): Promise<bigint>;
    changeAdminPassword(currentPassword: string, newPassword: string): Promise<boolean>;
    deleteBlogPost(id: bigint): Promise<boolean>;
    deleteExperience(id: bigint): Promise<boolean>;
    deleteMediaItem(id: bigint): Promise<boolean>;
    deleteProject(id: bigint): Promise<boolean>;
    getAllContacts(): Promise<Array<ContactSubmission>>;
    getAllExperiences(): Promise<Array<Experience>>;
    getAllMediaItems(): Promise<Array<MediaItem>>;
    getAllPosts(): Promise<Array<BlogPost>>;
    getAllProjects(): Promise<Array<Project>>;
    getAnalytics(): Promise<AnalyticsData>;
    getFeaturedPost(): Promise<BlogPost | null>;
    getPostsByCategory(category: string): Promise<Array<BlogPost>>;
    getProfileMeta(): Promise<ProfileMeta>;
    getResumeContent(): Promise<ResumeContent>;
    getSkillCategories(): Promise<Array<SkillCategory>>;
    initializeBlogs(): Promise<void>;
    initializeData(): Promise<void>;
    initializeExperiences(): Promise<void>;
    initializeMediaItems(): Promise<void>;
    initializeProjects(): Promise<void>;
    initializeSkills(): Promise<void>;
    recordBlogView(id: bigint): Promise<void>;
    recordProjectView(id: bigint): Promise<void>;
    recordResumeDownload(): Promise<void>;
    recordVisit(): Promise<void>;
    submitContact(name: string, email: string, message: string, timestamp: bigint): Promise<void>;
    updateBlogPost(id: bigint, title: string, category: string, summary: string, content: string, author: string, publishedAt: bigint, isFeatured: boolean, fileUrl: string): Promise<boolean>;
    updateExperience(id: bigint, title: string, company: string, badge: string, date: string, description: string, tags: Array<string>, accentColor: string): Promise<boolean>;
    updateMediaItem(id: bigint, title: string, category: string, caption: string, mediaUrl: string, mediaType: string, itemOrder: bigint): Promise<boolean>;
    updateProfileMeta(profileImageUrl: string, instagram: string, currentlyBuilding: string): Promise<void>;
    updateProject(id: bigint, title: string, techStack: Array<string>, description: string, category: string, githubUrl: string, demoUrl: string): Promise<boolean>;
    updateResumeContent(name: string, tagline: string, about: string, careerObjective: string, resumeFileUrl: string, email: string, linkedin: string, github: string): Promise<void>;
    updateSkillCategory(id: bigint, name: string, accentColor: string, skills: Array<Skill>): Promise<boolean>;
    verifyAdminPassword(password: string): Promise<boolean>;
}
import type { BlogPost as _BlogPost } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: boolean, arg7: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addExperience(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addExperience(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExperience(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addMediaItem(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addProject(arg0: string, arg1: Array<string>, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async changeAdminPassword(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminPassword(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminPassword(arg0, arg1);
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteExperience(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExperience(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExperience(arg0);
            return result;
        }
    }
    async deleteMediaItem(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaItem(arg0);
            return result;
        }
    }
    async deleteProject(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async getAllContacts(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllExperiences(): Promise<Array<Experience>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExperiences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExperiences();
            return result;
        }
    }
    async getAllMediaItems(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMediaItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMediaItems();
            return result;
        }
    }
    async getAllPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPosts();
            return result;
        }
    }
    async getAllProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProjects();
            return result;
        }
    }
    async getAnalytics(): Promise<AnalyticsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics();
            return result;
        }
    }
    async getFeaturedPost(): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedPost();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedPost();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostsByCategory(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostsByCategory(arg0);
            return result;
        }
    }
    async getProfileMeta(): Promise<ProfileMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfileMeta();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfileMeta();
            return result;
        }
    }
    async getResumeContent(): Promise<ResumeContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getResumeContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResumeContent();
            return result;
        }
    }
    async getSkillCategories(): Promise<Array<SkillCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSkillCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSkillCategories();
            return result;
        }
    }
    async initializeBlogs(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeBlogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeBlogs();
            return result;
        }
    }
    async initializeData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeData();
            return result;
        }
    }
    async initializeExperiences(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeExperiences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeExperiences();
            return result;
        }
    }
    async initializeMediaItems(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMediaItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMediaItems();
            return result;
        }
    }
    async initializeProjects(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeProjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeProjects();
            return result;
        }
    }
    async initializeSkills(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSkills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSkills();
            return result;
        }
    }
    async recordBlogView(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordBlogView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordBlogView(arg0);
            return result;
        }
    }
    async recordProjectView(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordProjectView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordProjectView(arg0);
            return result;
        }
    }
    async recordResumeDownload(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordResumeDownload();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordResumeDownload();
            return result;
        }
    }
    async recordVisit(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVisit();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVisit();
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: boolean, arg8: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateExperience(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: Array<string>, arg7: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExperience(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExperience(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateMediaItem(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMediaItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMediaItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateProfileMeta(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileMeta(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileMeta(arg0, arg1, arg2);
            return result;
        }
    }
    async updateProject(arg0: bigint, arg1: string, arg2: Array<string>, arg3: string, arg4: string, arg5: string, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateResumeContent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateResumeContent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateResumeContent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async updateSkillCategory(arg0: bigint, arg1: string, arg2: string, arg3: Array<Skill>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSkillCategory(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSkillCategory(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async verifyAdminPassword(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyAdminPassword(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
